query Mediathek {
  Mediatheks {
    docs {
      title
      type
       channel {
        name
        country
      }
      poster
      backdrop
      heroimage
      coverimage
      streamlink
      streamformat
      quality
    }
  }
}